# -*- coding: utf-8 -*-
"""aprovado e reprovado.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18bOdVrj8oL3vERYMCcwn6eP3G-v-8tOn
"""

media = 8.5

if(media>=7.0):
  resultado = "Aprovado"
elif(media>=5):
   resultado = "Em recuperação"
else:
  resultado = "Reprovado"

print(f'O estudante está: {resultado}')